/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/Users/huangcheng/hc/days/node_modules/.1.4.0@@vuepress/core/lib/client/root-mixins/updateMeta.js"
import m1 from "/Users/huangcheng/hc/days/node_modules/.1.4.0@@vuepress/plugin-active-header-links/clientRootMixin.js"
import m2 from "/Users/huangcheng/hc/days/node_modules/.1.4.0@@vuepress/plugin-nprogress/clientRootMixin.js"
import m3 from "/Users/huangcheng/hc/days/node_modules/.1.4.0@@vuepress/plugin-medium-zoom/clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]