/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "timg.png",
        "actionText": "开始 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简单",
            "details": "事情做到简单"
          },
          {
            "title": "极致",
            "details": "事情做到极致。"
          },
          {
            "title": "为善",
            "details": "以善行天下。"
          }
        ],
        "footer": "黄家二少爷"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0748c0b6",
      "path": "/"
    },
    {
      "title": "指南使用手册",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-09581d8b",
      "path": "/guide/"
    },
    {
      "title": "webpack组件复用指南",
      "frontmatter": {},
      "regularPath": "/guide/webpack.html",
      "relativePath": "guide/webpack.md",
      "key": "v-0b3783d6",
      "path": "/guide/webpack.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/preface.html",
      "relativePath": "guide/preface.md",
      "key": "v-62a67776",
      "path": "/guide/preface.html"
    }
  ],
  "themeConfig": {
    "repo": "xiaomuzhu/front-end-interview",
    "editLinks": true,
    "locales": {
      "/": {
        "editLinkText": "在 GitHub 上编辑此页",
        "nav": [
          {
            "text": "指南",
            "link": "/guide/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "前言",
              "collapsable": false,
              "children": [
                "",
                "preface"
              ]
            },
            {
              "title": "webpack",
              "collapsable": false,
              "children": [
                "webpack"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "我的前端记录",
      "description": "自己的前端记录",
      "path": "/"
    }
  }
}