/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/boot/",
  "pages": [
    {
      "title": "开始",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-09581d8b",
      "path": "/guide/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "前端笔记",
        "actionLink": "/guide/",
        "<!-- features": [
          {
            "title": "简单",
            "details": "事情做到简单"
          },
          {
            "title": "极致",
            "details": "事情做到极致。"
          },
          {
            "title": "为善",
            "details": "与人为善。 -->"
          }
        ],
        "<!-- footer": "二少爷 -->"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0748c0b6",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/frame/webpack.html",
      "relativePath": "guide/frame/webpack.md",
      "key": "v-40c86e16",
      "path": "/guide/frame/webpack.html"
    },
    {
      "title": "算法",
      "frontmatter": {},
      "regularPath": "/guide/algorithm/",
      "relativePath": "guide/algorithm/README.md",
      "key": "v-e4f961ea",
      "path": "/guide/algorithm/"
    },
    {
      "title": "前端工程化",
      "frontmatter": {},
      "regularPath": "/guide/frame/",
      "relativePath": "guide/frame/README.md",
      "key": "v-a93ef6e2",
      "path": "/guide/frame/"
    },
    {
      "title": "面试相关",
      "frontmatter": {},
      "regularPath": "/guide/frame/interview.html",
      "relativePath": "guide/frame/interview.md",
      "key": "v-ef2924d4",
      "path": "/guide/frame/interview.html"
    },
    {
      "title": "你不知道的js",
      "frontmatter": {},
      "regularPath": "/guide/js/",
      "relativePath": "guide/js/README.md",
      "key": "v-c78fffd6",
      "path": "/guide/js/"
    },
    {
      "title": "开始",
      "frontmatter": {},
      "regularPath": "/guide/interview/",
      "relativePath": "guide/interview/README.md",
      "key": "v-22f71be7",
      "path": "/guide/interview/"
    },
    {
      "title": "作用域和闭包",
      "frontmatter": {},
      "regularPath": "/guide/js/zcop.html",
      "relativePath": "guide/js/zcop.md",
      "key": "v-43f60d76",
      "path": "/guide/js/zcop.html",
      "headers": [
        {
          "level": 3,
          "title": "理解作用域",
          "slug": "理解作用域"
        },
        {
          "level": 2,
          "title": "函数作用域和快作用域",
          "slug": "函数作用域和快作用域"
        },
        {
          "level": 2,
          "title": "提升",
          "slug": "提升"
        },
        {
          "level": 2,
          "title": "闭包",
          "slug": "闭包"
        }
      ]
    },
    {
      "title": "ES6 增加的属性",
      "frontmatter": {},
      "regularPath": "/guide/js/es6.html",
      "relativePath": "guide/js/es6.md",
      "key": "v-3e365ad8",
      "path": "/guide/js/es6.html",
      "headers": [
        {
          "level": 2,
          "title": "ES2015",
          "slug": "es2015"
        },
        {
          "level": 3,
          "title": "声明",
          "slug": "声明"
        },
        {
          "level": 3,
          "title": "解构赋值",
          "slug": "解构赋值"
        },
        {
          "level": 3,
          "title": "字符串扩展",
          "slug": "字符串扩展"
        },
        {
          "level": 3,
          "title": "数值扩展",
          "slug": "数值扩展"
        },
        {
          "level": 3,
          "title": "对象扩展",
          "slug": "对象扩展"
        },
        {
          "level": 3,
          "title": "函数扩展",
          "slug": "函数扩展"
        },
        {
          "level": 3,
          "title": "正则扩展",
          "slug": "正则扩展"
        },
        {
          "level": 3,
          "title": "Symbol",
          "slug": "symbol"
        },
        {
          "level": 3,
          "title": "Set",
          "slug": "set"
        },
        {
          "level": 3,
          "title": "map",
          "slug": "map"
        },
        {
          "level": 3,
          "title": "Proxy",
          "slug": "proxy"
        },
        {
          "level": 3,
          "title": "Reflect",
          "slug": "reflect"
        },
        {
          "level": 3,
          "title": "class",
          "slug": "class"
        },
        {
          "level": 3,
          "title": "Module",
          "slug": "module"
        },
        {
          "level": 3,
          "title": "Iterator",
          "slug": "iterator"
        },
        {
          "level": 3,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 3,
          "title": "Generator",
          "slug": "generator"
        },
        {
          "level": 2,
          "title": "ES2016",
          "slug": "es2016"
        },
        {
          "level": 3,
          "title": "数值扩展",
          "slug": "数值扩展-2"
        },
        {
          "level": 3,
          "title": "数组扩展",
          "slug": "数组扩展"
        },
        {
          "level": 2,
          "title": "ES2017",
          "slug": "es2017"
        },
        {
          "level": 3,
          "title": "声明",
          "slug": "声明-2"
        },
        {
          "level": 3,
          "title": "字符串扩展",
          "slug": "字符串扩展-2"
        },
        {
          "level": 3,
          "title": "对象扩展",
          "slug": "对象扩展-2"
        },
        {
          "level": 3,
          "title": "函数扩展",
          "slug": "函数扩展-2"
        },
        {
          "level": 3,
          "title": "Async",
          "slug": "async"
        },
        {
          "level": 2,
          "title": "ES2018",
          "slug": "es2018"
        },
        {
          "level": 3,
          "title": "字符串扩展",
          "slug": "字符串扩展-3"
        },
        {
          "level": 3,
          "title": "对象扩展",
          "slug": "对象扩展-3"
        },
        {
          "level": 3,
          "title": "正则扩展",
          "slug": "正则扩展-2"
        },
        {
          "level": 3,
          "title": "Promise",
          "slug": "promise-2"
        },
        {
          "level": 3,
          "title": "Async",
          "slug": "async-2"
        },
        {
          "level": 2,
          "title": "ES2019",
          "slug": "es2019"
        },
        {
          "level": 3,
          "title": "字符串扩展",
          "slug": "字符串扩展-4"
        },
        {
          "level": 3,
          "title": "多想扩展",
          "slug": "多想扩展"
        },
        {
          "level": 3,
          "title": "数组扩展",
          "slug": "数组扩展-2"
        },
        {
          "level": 3,
          "title": "函数扩展",
          "slug": "函数扩展-3"
        },
        {
          "level": 3,
          "title": "symbol",
          "slug": "symbol-2"
        }
      ]
    },
    {
      "title": "管理成长",
      "frontmatter": {},
      "regularPath": "/guide/manage/",
      "relativePath": "guide/manage/README.md",
      "key": "v-8a0fffd6",
      "path": "/guide/manage/"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/mode/",
      "relativePath": "guide/mode/README.md",
      "key": "v-1c4287d6",
      "path": "/guide/mode/"
    },
    {
      "title": "react面试",
      "frontmatter": {},
      "regularPath": "/guide/react/interview.html",
      "relativePath": "guide/react/interview.md",
      "key": "v-503a0d56",
      "path": "/guide/react/interview.html"
    },
    {
      "title": "react学习",
      "frontmatter": {},
      "regularPath": "/guide/react/",
      "relativePath": "guide/react/README.md",
      "key": "v-8bf39b2a",
      "path": "/guide/react/"
    },
    {
      "title": "小程序笔记",
      "frontmatter": {},
      "regularPath": "/guide/xcx/",
      "relativePath": "guide/xcx/README.md",
      "key": "v-7d732e62",
      "path": "/guide/xcx/"
    },
    {
      "title": "浏览器相关",
      "frontmatter": {},
      "regularPath": "/guide/browser/browser.html",
      "relativePath": "guide/browser/browser.md",
      "key": "v-786ed954",
      "path": "/guide/browser/browser.html",
      "headers": [
        {
          "level": 2,
          "title": "浏览器事件机制",
          "slug": "浏览器事件机制"
        },
        {
          "level": 3,
          "title": "事件传播",
          "slug": "事件传播"
        },
        {
          "level": 3,
          "title": "阻止冒泡和默认事件",
          "slug": "阻止冒泡和默认事件"
        },
        {
          "level": 3,
          "title": "事件回调",
          "slug": "事件回调"
        }
      ]
    },
    {
      "title": "vue学习",
      "frontmatter": {},
      "regularPath": "/guide/vue/",
      "relativePath": "guide/vue/README.md",
      "key": "v-04d2905d",
      "path": "/guide/vue/"
    },
    {
      "title": "开发注意",
      "frontmatter": {},
      "regularPath": "/guide/xcx/notice.html",
      "relativePath": "guide/xcx/notice.md",
      "key": "v-b3200a30",
      "path": "/guide/xcx/notice.html"
    },
    {
      "title": "小程序中如何实现抖音的无限滑动效果",
      "frontmatter": {},
      "regularPath": "/guide/xcx/swiper.html",
      "relativePath": "guide/xcx/swiper.md",
      "key": "v-1d6a20b0",
      "path": "/guide/xcx/swiper.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/mode/feat.html",
      "relativePath": "guide/mode/feat.md",
      "key": "v-78d4c4f6",
      "path": "/guide/mode/feat.html"
    }
  ],
  "themeConfig": {
    "repo": "huangxiaoyaoguai/days",
    "editLinks": false,
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ],
    "locales": {
      "/": {
        "editLinkText": "在 GitHub 上编辑此页",
        "nav": [
          {
            "text": "指南",
            "link": "/guide/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "前言",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "浏览器",
              "collapsable": false,
              "children": [
                "browser/browser"
              ]
            },
            {
              "title": "设计模式",
              "collapsable": false,
              "children": [
                "mode/",
                "mode/feat"
              ]
            },
            {
              "title": "前端工程化",
              "collapsable": false,
              "children": [
                "frame/",
                "frame/interview"
              ]
            },
            {
              "title": "js",
              "collapsable": false,
              "children": [
                "js/",
                "js/es6"
              ]
            },
            {
              "title": "小程序",
              "collapsable": false,
              "children": [
                "xcx/",
                "xcx/swiper",
                "xcx/notice"
              ]
            },
            {
              "title": "react",
              "collapsable": false,
              "children": [
                "react/",
                "react/interview"
              ]
            },
            {
              "title": "vue",
              "collapsable": false,
              "children": [
                "vue/"
              ]
            },
            {
              "title": "算法",
              "collapsable": false,
              "children": [
                "algorithm/"
              ]
            },
            {
              "title": "管理",
              "collapsable": false,
              "children": [
                "manage/"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "二少爷的笔记",
      "description": "好想做一个顽固的少爷，每天游手好闲，不学无术，多自在。",
      "path": "/"
    }
  }
}