/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/boot/",
  "pages": [
    {
      "title": "浏览器相关",
      "frontmatter": {},
      "regularPath": "/guide/browser/browser.html",
      "relativePath": "guide/browser/browser.md",
      "key": "v-86834984",
      "path": "/guide/browser/browser.html",
      "headers": [
        {
          "level": 2,
          "title": "浏览器事件机制",
          "slug": "浏览器事件机制"
        },
        {
          "level": 3,
          "title": "事件传播",
          "slug": "事件传播"
        },
        {
          "level": 3,
          "title": "阻止冒泡和默认事件",
          "slug": "阻止冒泡和默认事件"
        },
        {
          "level": 3,
          "title": "事件回调",
          "slug": "事件回调"
        }
      ]
    },
    {
      "title": "开始",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-953666ba",
      "path": "/guide/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "前端笔记",
        "actionLink": "/guide/",
        "<!-- features": [
          {
            "title": "简单",
            "details": "事情做到简单"
          },
          {
            "title": "极致",
            "details": "事情做到极致。"
          },
          {
            "title": "为善",
            "details": "与人为善。 -->"
          }
        ],
        "<!-- footer": "二少爷 -->"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5b6432bd",
      "path": "/"
    },
    {
      "title": "webpack组件复用指南11111",
      "frontmatter": {},
      "regularPath": "/guide/webpack/webpack.html",
      "relativePath": "guide/webpack/webpack.md",
      "key": "v-6c66b3fe",
      "path": "/guide/webpack/webpack.html"
    }
  ],
  "themeConfig": {
    "repo": "huangxiaoyaoguai/days",
    "editLinks": false,
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ],
    "locales": {
      "/": {
        "editLinkText": "在 GitHub 上编辑此页",
        "nav": [
          {
            "text": "指南",
            "link": "/guide/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "前言",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "浏览器",
              "collapsable": false,
              "children": [
                "browser/browser"
              ]
            },
            {
              "title": "前端工程化",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "js",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "前端框架",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "小程序",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "react",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "vue",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "算法",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "管理",
              "collapsable": false,
              "children": [
                ""
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "二少爷",
      "description": "好想做一个顽固的少爷，每天游手好闲，不学无术，多自在。",
      "path": "/"
    }
  }
}